name: Build Master

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          #- 4.10.x
          - ocaml-variants.4.11.2+flambda
          #- ocaml-variants.4.12.0+options,ocaml-option-flambda
        opam-disable-sandboxing:
          - true
        dune-cache: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      # checking out the code seems to be important because local switch is used
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0                      # fix me later

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        #uses: ocaml/setup-ocaml@v2
        uses: ocaml/setup-ocaml@5319ab427f3840efb109b436a4e6f047dcd9db9f
          # working around issue with depext and opam 2.1
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Installing dependencies
        run: |
          opam install . --deps-only --with-test --with-doc

      - name: Building...
        run: |
          opam exec -- dune build

      - name: Running tests...
        run: |
          opam exec -- dune runtest

      - name: Build API documentation
        run: opam exec -- dune build @doc

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html
          keep_files: true
          destination_dir: api

      - name: Build linter descriptions...
        run: mkdir -p _build/_lintinfo && opam exec -- dune exec -- src/mylint.exe -dump-lints _build/_lintinfo/lints.json

      - name: Deploy linters' descriptions
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/_lintinfo
          keep_files: true
          destination_dir: lints

      - name: Deploy linters' descriptions to another repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.A_TOKEN_TO_PUSH_DOC_TO_ANOTHER_REPO }}
          publish_dir: _build/_lintinfo
          external_repository: Kakadu/kakadu.github.io
          keep_files: true
          destination_dir: zanuda
